### ISSUE TITLE
Review the CI

### ISSUE THREAD

**Issue by jmg-duarte** [jmg-duarte/pseudonym#5]
All tests need to pass and ideally the deprecation warnings should be shutdown as they are _precisely what is being tested_

**Comment by haennes** [comment]
I would suggest using the [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) tooling as it seems to be the most sophisticated and widely supported (lots of the actions mentioned below use it in their example code)

Should rustfmt just point out the formatting mistakes or immediately apply them upon merging?
I have found multiple actions providing the highlighting:
- [Run Rustfmt and Annotate](https://github.com/marketplace/actions/run-rustfmt-and-annotate)
- [Check formatting of Rust code with rustfmt](https://github.com/marketplace/actions/check-formatting-of-rust-code-with-rustfmt) -> would probably need another toolchain to the setup of the other CIs
- [rustfmt-check](https://github.com/marketplace/actions/rustfmt-check) -> requires nightly

and one immediately correcting it:
- [rust-rustfmt-check](https://github.com/marketplace/actions/rust-rustfmt-check) -> seems dead


For clippy there are the following options.
Just checking:
- [clippy Action](https://github.com/marketplace/actions/clippy-action)
- [clippy-check](https://github.com/marketplace/actions/clippy-check) -> great features for configuring the allow, warn, deny and forbid attributes (but should they even be configured in the CI instead of directly in the code (where needed))
- [qs-rust-clippy](https://github.com/marketplace/actions/qs-rust-clippy) -> supports rust versions in a different way
- [rust-clippy-check](https://github.com/marketplace/actions/rust-clippy-check) -> Will not post annotations for PRs from forked repos

running together with reviewdog:
- [Run Clippy with reviewdog](https://github.com/marketplace/actions/run-clippy-with-reviewdog)
- [clippy with reviewdog](https://github.com/marketplace/actions/clippy-with-reviewdog)

automatically creates a PR with the lints applied:
- [apply-clippy-lints](https://github.com/marketplace/actions/apply-clippy-lints)

**Comment by jmg-duarte** [comment]
Thanks for taking a look!

The rust-toolchain action should be enough to setup `rustfmt` and `clippy`, take a look at the components section in the README.

The action can then simply call `rustfmt --check` accordingly.

W.r.t. clippy, using reviewdog seems interesting and I'd be down to test it, the config that seems the most adequate is https://github.com/reviewdog/reviewdog#option-1-run-reviewdog-from-github-actions-w-secretsgithub_token.

I don't want any auto apply though, the code should only be changed by a person, adding a bot in the process may add entropy
